name: faithwave_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  bloc_test: ^9.1.7
  equatable: ^2.0.5
  toml: ^0.16.0
  shared_preferences: ^2.3.2
  flutter_easyloading: ^3.0.5
  pocketbase: ^0.21.0
  oxidized: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/